---
ID: "cbeccb13-ed1f-43a1-9a33-daacc4284013"
Parent: "39a55378-aeb2-4b41-ac69-4039e5d571db"
Template: "39a55378-aeb2-4b41-ac69-4039e5d571db"
Path: /sitecore/templates/Project/SamplePageTags/Tagging/_Taggable/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190302T145500Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
